### PR TITLE
New features: Sensitivity analysis

### LINKED ISSUE #10: Ability to return Jacobians and Sensitivity Matrices
This will require adding hard coding partial derivatives for each built in propensity type:
Jacobian: $\frac{d \rho_i(s)}{ds_j}$ for each species $s_j$
Sensitivity Matrix: $\frac{d \rho_i(s)}{dk}$ for each parameter (of that propensity) $k$.

Note: we will also need a check to make sure parameters aren't changing due to rules. If rules effect parameters, the sensitivity matrix will not be accurate and a warning should be given.

### PR DESCRIPTION
**Pull request by ayush9pandey**
This PR adds new features related to local sensitivity analysis of bioscrape models:

* Compute the Jacobian matrix at any point in the system trajectory (i.e. at a given state value).
* Compute the sensitivity of the model to any parameter at any given point in trajectory.
* Building on the two above, compute the sensitivity coefficient matrix that gives the sensitivity of the model with respect to each parameter at all time points for all states.

New tests are added as well as a jupyter notebook demonstrating a simple use case. 

The PR will fix #10

### CODE REVIEW

**Review by WilliamIX — APPROVED** [review]
This looks good! I'd still love to know if we can pass it the jacobian into ODE int....

**Comment by ayush9pandey** [comment]
> This looks good! I'd still love to know if we can pass it the jacobian into ODE int....

I looked into that a bit and it definitely seems possible from the code point of view but 
1. We would need a proper example to demonstrate how Jacobian helps with odeint
2. Maybe need some Cythonizing before we implement this because in that case odeint will evaluate the Jacobian function at every time point.

**Comment by ayush9pandey** [comment]
We can merge this and release the new version now..this is all I have from my end.

**Comment by WilliamIX** [comment]
merged!

**Pull request merged**
