### PR TITLE
Inference updates, new features, and bug fixes

### LINKED ISSUE #104: Delay support for inference
Inference should support Bioscrape delays but it does not currently.

### PR DESCRIPTION
**Pull request by ayush9pandey**
1. Added MCMC diagnostics that get printed out after every run (can be stopped by setting `convergence_diagnostics = False`). Includes autocorrelation time and acceptance fraction of the chain. Fix for #91 (thanks @mkratz for suggestion)
2. Initial seed for MCMC chain can now be directly set by the user. Simply passing in the numpy array of initial parameter values to the `init_seed` argument works. Alternatively, a float number can be passed into this argument that creates a Gaussian ball (of radius passed in as `init_seed`) around the initial values set in the Model object. Fix for #92 
3. LMFit added as a possible inference method. Detailed documentation in the corresponding notebook in `inference examples` directory.
4. Refactored the old "emcee_interface.py" to a new name file "inference_setup.py" since this file sets up inference for `emcee` and `lmfit` as well.
5. Fixed bugs with data for multiple measurements not loading correctly and initial condition related bugs as well (thanks to Cindy and Noah for pointing it out) 
6. For uniform and log uniform priors, I now return the uniform probability density (1/(b-a)) when the values lie within the bounds. This would not change any result as the probability returned is constant, so this change is only for being theoretically correct.
7. Fixed bug with Gaussian prior in issue #79  (thanks to James Parkin @boospooky for pointing it out)
8. Added multiple tutorial notebooks for inference, in particular, for least squares fit using LMfit.
9. Delay support now available with inference to fix #104. (needs a fix for delay simulator). See #103

### CODE REVIEW

**Comment by WilliamIX** [comment]
There is a bug in bioscrape inference getting started:

This cell:
`# from bioscrape.pid_interfaces import 
from bioscrape.inference import py_inference

# Import data from CSV
# Import a CSV file for each experiment run
prior = {'m' : ['gaussian', m_true, 500],'b' : ['gaussian', b_true, 1000]}
sampler, pid = py_inference(Model = M, exp_data = exp_data, measurements = ['y'],
                     time_column = ['x'], params_to_estimate = ['m','b'],
                      nwalkers = 32, nsteps = 2000, init_seed = 1e-4, prior = prior,
                      sim_type = 'deterministic', plot_show = False)

# Recommended to simply use sampler object/mcmc_results.csv and generate your own custom plots
truth_list, uncertainty_list = pid.plot_mcmc_results(sampler);`

Produced this error:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
bioscrape\types.pyx in bioscrape.types.Model.check_parameters()

ValueError: Unspecified Parameters: _b=nan, _m=nan

Exception ignored in: 'bioscrape.types.Model._initialize'
Traceback (most recent call last):
  File "bioscrape\types.pyx", line 1906, in bioscrape.types.Model.check_parameters
ValueError: Unspecified Parameters: _b=nan, _m=nan
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: Model has been changed since CSimInterface instantiation. CSimInterface no longer valid.

Exception ignored in: 'bioscrape.simulator.ModelCSimInterface.check_interface'
RuntimeError: Model has been changed since CSimInterface instantiation. CSimInterface no longer valid.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-641bc381da25> in <module>
      8                      time_column = ['x'], params_to_estimate = ['m','b'],
      9                       nwalkers = 32, nsteps = 2000, init_seed = 1e-4, prior = prior,
---> 10                       sim_type = 'deterministic', plot_show = False)
     11 
     12 # Recommended to simply use sampler object/mcmc_results.csv and generate your own custom plots

bioscrape\inference.pyx in bioscrape.inference.py_inference()

C:\ProgramData\Anaconda3\lib\site-packages\bioscrape\inference_setup.py in run_mcmc(self, **kwargs)
    235     def run_mcmc(self, **kwargs):
    236         self.prepare_inference(**kwargs)
--> 237         sampler = self.run_emcee(**kwargs)
    238         return sampler
    239 

C:\ProgramData\Anaconda3\lib\site-packages\bioscrape\inference_setup.py in run_emcee(self, **kwargs)
    386         assert p0.shape == (self.nwalkers, ndim)
    387         sampler = emcee.EnsembleSampler(self.nwalkers, ndim, self.cost_function)
--> 388         sampler.run_mcmc(p0, self.nsteps, progress = progress)
    389         if convergence_check:
    390             self.autocorrelation_time = sampler.get_autocorr_time()

C:\ProgramData\Anaconda3\lib\site-packages\emcee\sampler.py in run_mcmc(self, pos0, N, rstate0, lnprob0, **kwargs)
    170 
    171         for results in self.sample(pos0, lnprob0, rstate0, iterations=N,
--> 172                                    **kwargs):
    173             pass
    174 

TypeError: sample() got an unexpected keyword argument 'progress'`

Note: I am on the Inference-dev branch via the PR you made.

**Comment by ayush9pandey** [comment]
> 
> There is a bug in bioscrape inference getting started:

Looks like you have older emcee version. Can you try updating it and run again?

**Comment by ayush9pandey** [comment]
I added emcee version requirement to requirements.py.

**Review by WilliamIX — CHANGES_REQUESTED** [review]
Got everything working on my end - upgrading emcee worked (although as a note, to upgrade it people might have to delete the files in anacaond/site-packages then reinstall, pip uninstall and pip upgrade did not work).

Love the new inference notebook - I really think this does a good job streamlining the functionality!

My only request is with regards to testing. Could you add tests to make sure:
* all the different priors run
* the different options (multiple trajectories, initial conditions, etc) run
* Stochastic inference runs

I completely understand your concern about tests taking a long time and have a couple of ideas for how to make this manageable:
1.  do a super simple example like X <--> Y with a constrained state these examples should run faster than a birth death process. 
2. Alternatively, you could just use your linear fit code or do a very sloppy fit (low walkers, few steps) 
3. just ensure that the package runs smoothly, not the quality of the results.

**Comment by ayush9pandey** [comment]
Added ~10 new tests for inference.

**Review by WilliamIX — APPROVED** [review]

**Pull request merged**
