### PR TITLE
update for NumPy 2.0

### PR DESCRIPTION
**Pull request by murrayrm**
This PR updates bioscrape to work with NumPy 2.0 and seems to be mainly working on Python 3.12.

There is an error in one of the unit tests associated with Cython 3.0's handling of **.  The error message says that we need to set the compiler directive 'cpow(True)', but I was not able to do this.

Posting this how so that @ayush9pandey can see if this addresses issue #172.

### CODE REVIEW

**Comment by murrayrm** [comment]
Unit tests are failing, but it looks like they are very old versions of Python.  Probably need to be updated...

**Comment by ayush9pandey** [comment]
Thanks! I'll update the unit tests and try to fix the Cython error.

**Comment by ayush9pandey** [comment]
Fixed in https://github.com/murrayrm/bioscrape/pull/1

**Comment by murrayrm** [comment]
@ayush9pandey Looks like we are still checking against Python 3.7 and getting an error.

**Comment by ayush9pandey** [comment]
Yes, it's failing on Mac OS because it seems that it's defaulting to arm64 architecture for Mac OS now. It should work if we fix the architecture to x64 when testing on mac-os, with py3.7. Fixing it..

**Review by ayush9pandey — APPROVED** [review]
All tests pass!

**Review by ayush9pandey — APPROVED** [review]

**Pull request merged**
