### PR TITLE
Removing Bioscrape XML and adding SBML Functionality

### PR DESCRIPTION
**Pull request by WilliamIX**
- [x] Bioscrape XML writing removed (reading still supported for backwards compatibility)
- [x] Bioscrape XML examples removed 
- [x] Lineage simulation removed from the advanced examples (I forgot those were there)
- [x] Add delays and new rule types to SBML writing/reading with annotations
- [x] Add tests to ensure all SBML reading/writing work for all objects supported
- [x] Confirm underscores are consistently removed from the start of parameters and not added. Concerned about line 476 of sbmlutil.py (and there are some other places...) maybe we could test for this?

Linked to issues #99 #8 #107

### CODE REVIEW

**Comment by ayush9pandey** [comment]
@WilliamIX  This PR is now ready for review. I have added delay support and rule support with SBML (and added a bunch of tests for these). Other changes are minor and there's some refactoring of sbmlutil. Please feel free to add more tests wherever appropriate. 
also, have a look at issue #110 and let me know if we can fix it with this PR..

**Comment by ayush9pandey** [comment]
The ODE rule reading/writing is fixed now.

**Comment by WilliamIX** [comment]
This all looks good to me. @ayush9pandey can you please approve the PR whenever you are ready and we can release a new version of bioscrape?

**Comment by ayush9pandey** [comment]
Yes, I will take a look at everything once again, particularly for any old XML or underscores-to-parameter code.

**Review by ayush9pandey — APPROVED** [review]

**Comment by ayush9pandey** [comment]
All done! Let's merge this one.

**Pull request merged**
