### PR TITLE
C vector bug fix

### PR DESCRIPTION
**Pull request by WilliamIX**
This PR fixes issue #55 . The problem was that the c_propensity vector inside model was not being reset when new reactions were added. This resulted in a mismatch between the propensity vector and the stochiometric matrix. All the c_vectors are now reset appropriately and a test has been created to make sure models are working when initialize is called twice.

### CODE REVIEW

**Comment by ayush9pandey** [comment]
I guess this PR has changes from #68 as well, so it's probably better to merge #68 before this.

**Comment by WilliamIX** [comment]
> I guess this PR has changes from #68 as well, so it's probably better to merge #68 before this.
yep - agreed.

**Comment by ayush9pandey** [comment]
I guess once you fix merge conflicts the changes from #68 should not appear in the files changed tab.

**Comment by ayush9pandey** [comment]
Cool, now it all looks good! @rlwillia can you check that the issue you raised in #55 is fixed after this PR. You will have to get the latest code from dev branch and run setup.py install.

**Pull request merged**
